### ISSUE TITLE
fix for dnsomatic

### ISSUE THREAD

**Issue by kcasner** [jcostom/ddnsup#15]
Great work; best I've found. 

For DNS-0-Matic, there are undefined variables in ddnsup.py. Correcting the following lines resolves the issue and the record updates correctly.

```
DOM_USER = os.getenv('DOM_USER')
DOM_PASSWD = os.getenv('DOM_PASSWD')
DOM_WILDCARD = os.getenv('DOM_WILDCARD', 'NOCHG')
DOM_MX = os.getenv('DOM_MX', 'NOCHG')
DOM_BACKUPMX = os.getenv('DOM_BACKUPMX', 'NOCHG')`
```
Side note:
OpenDNS credentials are required. I signed up a long time ago and had DNS-O-Matic credentials. I feel it may help to mention that.

**Comment by jcostom** [comment]
Not really a bug, though I'll certainly grant you the naming convention could certainly be a bit more consistent.

If you check around line 45 of ddnsup.py, you'll find this:
```
    case 'dnsomatic':
        # Required Vars for DNS-O-Matic
        DOM_USER = os.getenv('DOMUSER')
        DOM_PASSWD = os.getenv('DOMPASSWD')
        DOM_WILDCARD = os.getenv('WILDCARD', 'NOCHG')
        DOM_MX = os.getenv('MX', 'NOCHG')
        DOM_BACKUPMX = os.getenv('BACKUPMX', 'NOCHG')
        # (possibly) redefine RECORDS - If you're using DNS-O-Matic and want to
        # update all services, you don't need to set RECORDS, we'll default to
        # all.dnsomatic.com, which does all your services.
        RECORDS = os.getenv('RECORDS', 'all.dnsomatic.com')
```

The vars you'd need to set in your environment are DOMUSER, DOMPASSWD, and optionally WILDCARD, MX, BACKUPMX, and RECORDS. Definitely 2 typo's in the example compose file, which I'll definitely commit to fixing. I'll look at some slightly more consistent variable naming, but doing so in a way that's backward compatible, so as not to break existing installs.

**Comment by kcasner** [comment]
Noticed. It looked like the DOM_ format was favored, so I went that route. To keep the source unmodified, I did update the yaml like you pointed out.

Saw an earlier commit mentioning plans to deprecate DNS-O-Matic. Hopefully it's decided to keep it. I tried 5 other clients, most broke, some spam updates, etc... Yours has everything going for it.

**Comment by jcostom** [comment]
So, my immediate thought is just to simply introduce these new vars as the "defaults" but keep supporting the old ones. Sort of like this:

DOM_USER = os.getenv(DOM_USER) or os.getenv('DOMUSER')

Thoughts? This would prevent someone using DOMUSER from breaking, while enabling some better normalization of variables.

**Comment by jcostom** [comment]
Hey - I just pushed a dev branch with all the variable normalization stuff. Take a look at the [README in the dev branch](https://github.com/jcostom/ddnsup/blob/dev/README.md), and take ghcr.io/jcostom/ddnsup:dev out for a spin. LMK if it's working the way you expect, ok?

**Comment by kcasner** [comment]
I was out of town, just caught up. Great solution; switched to :dev from :latest, used the config from dev, and it worked flawless first try. Awesome!

Side note: Noticed on the dev branch, the configs for dns-made-easy and dns-o-matic are missing ":latest" from the URL. Only an observation in differences; tested, does the same thing either way.

**Comment by jcostom** [comment]
Nice catch. Thanks. I'll update.
