### ISSUE TITLE
Bug: IndexError when updating root domain DNS record

### ISSUE THREAD

**Issue by Vergenter** [jcostom/ddnsup#24]
### Description:
When attempting to update the DNS record for the root domain (e.g., example.com), the script fails with an IndexError. This is caused by the get_cfdns_record_id function, which constructs an incorrect URL for root domain records and subsequently tries to access a non-existent element in the response.

### Steps to Reproduce:

1.    Configure the environment variables to update a root domain (e.g., example.com).
1.    Run the ddnsup service.
1.    Observe the following error in the logs:

```
Traceback (most recent call last):
  File "/app/ddnsup.py", line 335, in <module>
    main()
  File "/app/ddnsup.py", line 284, in main
    my_records[record_name] = get_cfdns_record_id(CF_ZONEID, CF_APITOKEN, record_name, my_domain)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/ddnsup.py", line 189, in get_cfdns_record_id
    return r.json()['result'][0]['id']
           ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
### Expected Behavior:
The script should correctly handle the root domain and update its DNS record without errors.

### Actual Behavior:
The script throws an IndexError because it constructs an incorrect URL for root domain records and attempts to access a non-existent element in the response.

### Code part with problem:
```py
def get_cfdns_record_id(zone_id: str, api_token: str, record_name: str,
                        domain_name: str) -> str:
    url = f"https://api.cloudflare.com/client/v4/zones/{zone_id}/dns_records?name={record_name}.{domain_name}"  # noqa E501
```
Here url simply cannot be correctly created for root level domain.

### Ugly fix:
```py
def get_cfdns_record_id(zone_id: str, api_token: str, record_name: str,
                        domain_name: str) -> str:
    # Check if the record name is the same as the domain name
    if record_name == domain_name:
        url = f"https://api.cloudflare.com/client/v4/zones/{zone_id}/dns_records?name={record_name}"
    else:
        url = f"https://api.cloudflare.com/client/v4/zones/{zone_id}/dns_records?name={record_name}.{domain_name}"
    
    r = create_cfdns_get_req(url, api_token)
    # Check if the result list is not empty before accessing its first element
    result = r.json().get('result')
    if not result:
        raise ValueError(f"DNS record not found for {record_name}.{domain_name}")
    return result[0]['id']
```

**Comment by jcostom** [comment]
Good catch here. I never really considered doing DDNS for a zone root record. I'm on the road for a couple of days but will get a look at this when I get back home. Thanks for the report!

**Comment by jcostom** [comment]
Standby - I'm merging the fix now. After that's done, I'll spin release v1.4, which includes the fix. Thanks @Vergenter !
