### ISSUE TITLE
Provide an path option for secrets

### ISSUE THREAD

**Issue by happysalada** [jcostom/ddnsup#5]
Hey, first of all, thanks a lot for making this!

Docker provides a mechanism for secret management, but it takes file_paths to read the values from.
Would it be possible to have the secrets also have an option to read from a path.
like adding API_KEY_PATH, and the script would read the value from a file path supplied ?
(incidentally systemd has a very similar system).

happy to give details on anything.

**Comment by jcostom** [comment]
Interesting idea. Not saying no, but wondering how this would be better than how it's managed presently. At least when I use this, everything's in a file already, namely the docker-compose file. You could also just use an env_file in your compose file as well, no?

**Comment by happysalada** [comment]
Im one of the maintainers of nixos and i was thinking if packaging this. The service would be packages as a systemd service and passing secrets as environment variable is quite frowned upon.
Dont worry about it though, if it works for you , keep it that way, i think ill just make a script that interacts with the cloudflare api since its the one i need.

**Comment by jcostom** [comment]
Gotcha! I only ever run this as a container, so I get your point now. I've got a sprawling to-do list at the moment, so it's def kind of back-burner, but interesting nonetheless.
